[project]
name = "life-record-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fei", email = "yoooman321@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
life-record-api = "life_record_api:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
