[project]
name = "life-record-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fei", email = "yoooman321@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "google-cloud-storage>=3.15.0",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.1",
    "sqlmodel>=0.0.45",
]

[project.scripts]
life-record-api = "life_record_api:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
